import Link from "next/link";
import { notFound } from "next/navigation";

import {
  isPrefixedLocale,
  prefixedLocales,
  type PrefixedLocale,
} from "@/i18n/locales";

type LocalizedHomePageProps = {
  params: Promise<{
    locale: string;
  }>;
};

type LocalizedHomeCopy = {
  title: string;
  description: string;
  statusLabel: string;
  body: string;
  nextStepsTitle: string;
  nextSteps: string[];
  japaneseLinkLabel: string;
};

const localizedHomeCopy: Record<PrefixedLocale, LocalizedHomeCopy> = {
  en: {
    title: "AWS Cert Roadmap Lab",
    description:
      "The English route is ready. Localized learning content will be added in the next Phase 5 tasks.",
    statusLabel: "Routing foundation",
    body:
      "This page confirms that the /en static route can be generated by Next.js static export. Terms, comparisons, architecture articles, and blog pages will be localized in later tasks.",
    nextStepsTitle: "Next implementation targets",
    nextSteps: [
      "Add English common pages",
      "Add English AWS terms",
      "Add English comparison articles",
      "Add English architecture articles",
    ],
    japaneseLinkLabel: "Back to Japanese site",
  },
  zh: {
    title: "AWS Cert Roadmap Lab",
    description:
      "繁體中文路由已準備完成。後續 Phase 5 任務會加入本地化學習內容。",
    statusLabel: "多語路由基礎",
    body:
      "此頁面用來確認 Next.js static export 可以產生 /zh 靜態路由。AWS 用語、比較文章、架構圖解與部落格文章會在後續任務中本地化。",
    nextStepsTitle: "後續實作目標",
    nextSteps: [
      "新增繁體中文共通頁面",
      "新增繁體中文 AWS 用語",
      "新增繁體中文比較文章",
      "新增繁體中文架構圖文章",
    ],
    japaneseLinkLabel: "返回日文網站",
  },
};

export function generateStaticParams() {
  return prefixedLocales.map((locale) => ({
    locale,
  }));
}

export default async function LocalizedHomePage({
  params,
}: LocalizedHomePageProps) {
  const { locale } = await params;

  if (!isPrefixedLocale(locale)) {
    notFound();
  }

  const copy = localizedHomeCopy[locale];

  return (
    <main className="mx-auto max-w-5xl px-6 py-16">
      <section className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold uppercase tracking-wide text-blue-600">
          {copy.statusLabel}
        </p>

        <h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-950">
          {copy.title}
        </h1>

        <p className="mt-4 max-w-3xl text-lg leading-8 text-slate-700">
          {copy.description}
        </p>

        <p className="mt-6 max-w-3xl leading-7 text-slate-600">{copy.body}</p>

        <div className="mt-8">
          <Link
            href="/"
            className="inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700"
          >
            {copy.japaneseLinkLabel}
          </Link>
        </div>
      </section>

      <section className="mt-10 rounded-3xl border border-slate-200 bg-slate-50 p-8">
        <h2 className="text-2xl font-bold text-slate-950">
          {copy.nextStepsTitle}
        </h2>

        <ul className="mt-5 grid gap-3 text-slate-700 sm:grid-cols-2">
          {copy.nextSteps.map((item) => (
            <li
              key={item}
              className="rounded-2xl border border-slate-200 bg-white p-4"
            >
              {item}
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}