import type { Comparison } from "../../types/comparison";

export const comparisons: Comparison[] = [
  {
    comparisonId: "cmp-001",
    slug: "s3-vs-ebs-vs-efs",
    title: "S3・EBS・EFSの違い",
    description:
      "AWSの代表的なストレージサービスであるS3、EBS、EFSの違いを、保存方式・主な用途・試験ポイントから比較します。",
    category: "Storage",
    level: "beginner",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["s3", "ebs", "efs"],
    tags: ["storage", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    comparisonId: "cmp-002",
    slug: "rds-vs-dynamodb",
    title: "RDS・DynamoDBの違い",
    description:
      "リレーショナルデータベースのRDSと、NoSQLデータベースのDynamoDBを、データ構造・スケーリング・コストの観点で比較します。",
    category: "Database",
    level: "beginner",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["rds", "dynamodb"],
    tags: ["database", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    comparisonId: "cmp-003",
    slug: "sns-vs-sqs-vs-eventbridge",
    title: "SNS・SQS・EventBridgeの違い",
    description:
      "AWSの代表的な連携サービスであるSNS、SQS、EventBridgeを、通知・キュー・イベントルーティングの違いから整理します。",
    category: "Integration",
    level: "beginner",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["sns", "sqs", "eventbridge"],
    tags: ["integration", "messaging", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    comparisonId: "cmp-004",
    slug: "iam-user-vs-role-vs-policy",
    title: "IAMユーザー・IAMロール・IAMポリシーの違い",
    description:
      "IAMユーザー、IAMロール、IAMポリシーの役割を整理し、AWS権限管理で何をどの場面で使うかを比較します。",
    category: "Security",
    level: "beginner",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["iam"],
    tags: ["security", "iam", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    comparisonId: "cmp-005",
    slug: "cloudwatch-vs-cloudtrail-vs-config",
    title: "CloudWatch・CloudTrail・AWS Configの違い",
    description:
      "監視、操作履歴、リソース設定管理の違いを整理し、CloudWatch、CloudTrail、AWS Configの使い分けを比較します。",
    category: "Monitoring",
    level: "beginner",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["cloudwatch", "cloudtrail", "config"],
    tags: ["monitoring", "governance", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    comparisonId: "cmp-006",
    slug: "alb-vs-nlb-vs-cloudfront",
    title: "ALB・NLB・CloudFrontの違い",
    description:
      "AWSの通信入口で混同しやすいApplication Load Balancer、Network Load Balancer、Amazon CloudFrontの違いを、試験ポイントと実務での使い分けから整理します。",
    category: "Networking",
    level: "intermediate",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["elb", "cloudfront"],
    tags: ["networking", "load-balancer", "cloudfront", "comparison", "clf", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    comparisonId: "cmp-007",
    slug: "multi-az-vs-read-replica",
    title: "RDS Multi-AZ・Read Replicaの違い",
    description:
      "Amazon RDSで混同しやすいMulti-AZ配置とRead Replicaの違いを、可用性、読み取り性能、フェイルオーバー、試験ポイントの観点で整理します。",
    category: "Database",
    level: "intermediate",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["rds"],
    tags: ["database", "rds", "multi-az", "read-replica", "comparison", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    comparisonId: "cmp-008",
    slug: "security-group-vs-nacl",
    title: "Security Group・Network ACLの違い",
    description:
      "Amazon VPCで混同しやすいSecurity GroupとNetwork ACLの違いを、適用範囲、ステートフル、ステートレス、許可・拒否ルールの観点で整理します。",
    category: "Security",
    level: "intermediate",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["vpc"],
    tags: ["security", "vpc", "security-group", "nacl", "comparison", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    comparisonId: "cmp-009",
    slug: "api-gateway-vs-alb-vs-cloudfront",
    title: "API Gateway・ALB・CloudFrontの違い",
    description:
      "AWSでAPIやWebアプリの入口として使われるAPI Gateway、Application Load Balancer、Amazon CloudFrontの違いを、サーバーレス、負荷分散、CDNの観点で整理します。",
    category: "Networking",
    level: "intermediate",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["api-gateway", "elb", "cloudfront"],
    tags: ["api", "serverless", "networking", "cloudfront", "comparison", "saa"],
    priority: "high",
    published: true,
    publishedAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    comparisonId: "cmp-010",
    slug: "secrets-manager-vs-parameter-store",
    title: "Secrets Manager・Parameter Storeの違い",
    description:
      "AWSで設定値や機密情報を管理するSecrets ManagerとSystems Manager Parameter Storeの違いを、用途、暗号化、自動ローテーション、コストの観点で整理します。",
    category: "Security",
    level: "intermediate",
    examScopes: ["CLF-C02", "SAA-C03"],
    services: ["secrets-manager", "systems-manager", "kms"],
    tags: ["security", "secrets", "parameter-store", "kms", "comparison", "saa"],
    priority: "medium",
    published: true,
    publishedAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
];

export const publishedComparisons = comparisons.filter(
  (comparison) => comparison.published,
);