var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/questions/[questionId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.6bxq1._.js")
R.c("server/chunks/ssr/contents_questions_clf-c02_json_[json]_cjs_09z4_gs._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0dq4l~8.js")
R.c("server/chunks/ssr/[root-of-the-server]__07079dt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/_0ucfc4l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_questions_[questionId]_page_actions_0bk..ik.js")
R.m(96431)
module.exports=R.m(96431).exports
