var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/[postSlug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v1vvqe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_068co.i.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07079dt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/_0ucfc4l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_[postSlug]_page_actions_0xsu3qp.js")
R.m(85107)
module.exports=R.m(85107).exports
