var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/terms/[termId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pot29g._.js")
R.c("server/chunks/ssr/_06y34yo._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~ubvum.js")
R.c("server/chunks/ssr/[root-of-the-server]__07079dt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/_0ucfc4l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_terms_[termId]_page_actions_044o0fe.js")
R.m(33112)
module.exports=R.m(33112).exports
